#!/usr/bin/python3


def replace_kerwords(source, keyword, keyword_replace):
    if keyword in source:
        for i in source:
            source = source.replace(keyword, keyword_replace)
    return source


source = input('input: ')
keywords = " `!@#$%^&*()_+-=\|{}:\"<>?;',/"
for i in keywords:
    source = replace_kerwords(source, i, '.')
    source = replace_kerwords(source, '..', '.')

print(source)
