#!/usr/bin/python3
result = input('input: ')
if ' ' in result:
  for i in result:
    result = result.replace(' ', '.')
if ':' in result:
  for i in result:
    result = result.replace(':', '.')
if '..' in result:
  for i in result:
    result = result.replace('..', '.')
print(result)
