#!/usr/bin/python3
result = input('input: ')


def replace_kerwords(source, keyword, keyword_replace):
    if keyword in source:
        for i in source:
            source = source.replace(keyword, keyword_replace)
    return source


result = replace_kerwords(result, ' ', '.')
result = replace_kerwords(result, ':', '.')
result = replace_kerwords(result, '：', '.')
result = replace_kerwords(result, '-', '.')

result = replace_kerwords(result, '..', '.')
print(result)
